## Start with importing consolidated data

In [59]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer


movies = pd.read_csv('./total_df.csv')

In [60]:
movies.isnull().sum()

title                0
Unnamed: 0         166
budget             166
genres             166
revenue            166
runtime            168
script             176
actor_1            180
actor_2            181
actor_3            181
director           177
rating             192
stars_out_of_10    179
writer             177
year               178
dtype: int64

In [61]:
#dropped all Nan values
movies.dropna(inplace = True) 

In [62]:
movies.shape

(1009, 15)

In [63]:
movies.head()

title  Unnamed: 0      budget  \
1  10 things i hate about you         0.0  16000000.0   
3              12 and holding         2.0    400000.0   
6            12 years a slave         4.0  20000000.0   
7                   127 hours         5.0  18000000.0   
8  1492: conquest of paradise         6.0  47000000.0   

                                              genres      revenue  runtime  \
1  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   53478166.0     97.0   
3                      [{'id': 18, 'name': 'Drama'}]      95687.0     90.0   
6  [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...  187000000.0    134.0   
7  [{'id': 12, 'name': 'Adventure'}, {'id': 18, '...   35692920.0     94.0   
8  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...    7191399.0    154.0   

                                              script           actor_1  \
1  \r\r\n\r\r\n\r\r\n\r\r\n<b><!--\r\r\n</b>if (w...      Heath Ledger   
3  \r\r\n           \r\r\n          \r\r\n       ...     Conor Donovan   
6  \r\r\n\r\r\r\n\r\r\r\n\r\r\r\n                ...  Chiwetel Ejiofor   
7  \r\r\n\r\r\r\n\r\r\r\n \r\r\r\n               ...      James Franco   
8  \r\r\n\r\r\n\r\r\n\r\r\n\r\r\n1492: Conquest o...  Gérard Depardieu   

                    actor_2               actor_3        director  \
1              Julia Stiles  Joseph Gordon-Levitt      Gil Junger   
3             Jesse Camacho        Zoe Weizenbaum  Michael Cuesta   
6  Michael Kenneth Williams    Michael Fassbender   Steve McQueen   
7             Amber Tamblyn             Kate Mara     Danny Boyle   
8            Armand Assante      Sigourney Weaver    Ridley Scott   

                                              rating  stars_out_of_10  \
1                  PG-13\r\r\n    | \r\r\n                        7.3   
3                                                                 7.6   
6                 R\r\r\n    | \r\r\n                             8.1   
7               R\r\r\n    | \r\r\n                               7.6   
8             PG-13\r\r\n    | \r\r\n            ...              6.5   

             writer    year  
1    Karen McCullah  1999.0  
3  Anthony Cipriano  2005.0  
6       John Ridley  2013.0  
7       Danny Boyle  2010.0  
8        Rose Bosch  1992.0

In [64]:
(movies['stars_out_of_10'] > movies['stars_out_of_10'].mean()).value_counts()

True     545
False    464
Name: stars_out_of_10, dtype: int64

In [65]:
def critical(row):
    if row['stars_out_of_10'] > movies['stars_out_of_10'].mean():
        value = 1
    else: 
        value = 0 
    return value

In [66]:
movies['critical_success'] = movies.apply(critical, axis = 1)

In [67]:
movies['critical_success'].value_counts()

1    545
0    464
Name: critical_success, dtype: int64

In [68]:
def success(row):
    if (row['revenue'] - row['budget']) > 20000000:
        value = 1
    else: 
        value = 0 
    return value

In [69]:
movies['financial_success'] = movies.apply(success, axis = 1)

In [70]:
((movies['revenue'] - movies['budget']) > 20000000).value_counts()

True     541
False    468
dtype: int64

In [71]:
movies.head(50)

title  Unnamed: 0       budget  \
1   10 things i hate about you         0.0   16000000.0   
3               12 and holding         2.0     400000.0   
6             12 years a slave         4.0   20000000.0   
7                    127 hours         5.0   18000000.0   
8   1492: conquest of paradise         6.0   47000000.0   
9                   15 minutes         7.0   60000000.0   
10                    17 again         8.0   20000000.0   
12       2001: a space odyssey        10.0   10500000.0   
13                        2012        11.0  200000000.0   
14                   25th hour        12.0   15000000.0   
16          30 minutes or less        13.0   28000000.0   
17                          42        14.0   40000000.0   
18               44 inch chest        15.0          0.0   
19                     48 hrs.        16.0   12000000.0   
23                      8 mile        19.0   41000000.0   
24                         8mm        20.0   40000000.0   
25                           9        21.0   30000000.0   
28              a few good men        22.0   40000000.0   
30         a most violent year        23.0   20000000.0   
33            a scanner darkly        24.0    8700000.0   
34               a serious man        25.0    7000000.0   
37               above the law        27.0    7500000.0   
38              absolute power        28.0   50000000.0   
39  ace ventura: pet detective        30.0   15000000.0   
42                  affliction        35.0    6000000.0   
43        after school special        36.0          0.0   
44                  after.life        37.0    4500000.0   
45                agnes of god        38.0          0.0   
46               air force one        39.0   85000000.0   
51                     aladdin        42.0   28000000.0   
52                         ali        43.0  107000000.0   
53                       alien        44.0   11000000.0   
55                alien nation        46.0   16000000.0   
59                      aliens        49.0   18500000.0   
61               all about eve        50.0    1400000.0   
62             all about steve        51.0   15000000.0   
63          all the king's men        52.0   55000000.0   
64     all the president's men        53.0    8500000.0   
65               almost famous        54.0   60000000.0   
66           alone in the dark        55.0   20000000.0   
67                     amadeus        56.0   18000000.0   
68                      amelia        57.0   40000000.0   
69             american beauty        58.0   15000000.0   
70           american gangster        59.0  100000000.0   
71           american graffiti        60.0     777000.0   
72          american history x        61.0   20000000.0   
73             american hustle        62.0   40000000.0   
74            american madness        63.0          0.0   
75          american milkshake        64.0          0.0   
76            american outlaws        65.0   35000000.0   

                                               genres      revenue  runtime  \
1   [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   53478166.0     97.0   
3                       [{'id': 18, 'name': 'Drama'}]      95687.0     90.0   
6   [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...  187000000.0    134.0   
7   [{'id': 12, 'name': 'Adventure'}, {'id': 18, '...   35692920.0     94.0   
8   [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...    7191399.0    154.0   
9   [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...   56359980.0    120.0   
10                     [{'id': 35, 'name': 'Comedy'}]  136267476.0    102.0   
12  [{'id': 878, 'name': 'Science Fiction'}, {'id'...   68700000.0    149.0   
13  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...  769653595.0    158.0   
14  [{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...   13060843.0    135.0   
16  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   40547440.0     83.0   
17                      [{'id': 18, 'name': 'Drama'}]   95020213.0 

In [73]:
(movies['critical_success'] + movies['financial_success']).value_counts()

1    392
2    347
0    270
dtype: int64

In [181]:
movies.to_csv('movies.csv', index = False)

# Count Vectorizer - Script Data

In [182]:
corpus2 = movies['script']
cvec = CountVectorizer(stop_words='english', min_df = 0.50, max_df = 0.99)

cvec.fit(corpus2)
all_scripts_corpus = cvec.transform(corpus2)
all_scripts_corpus

<1009x1313 sparse matrix of type '<class 'numpy.int64'>'
	with 943637 stored elements in Compressed Sparse Row format>

In [183]:
all_scripts_corpus.todense()

matrix([[  1,   0,   1, ...,   1,   7,   1],
        [  3,   1,   3, ...,   0,   4,   2],
        [  6,   7,   7, ...,   0,  20,   9],
        ...,
        [  3,   3,  12, ..., 106,   3,   1],
        [  0,   0,   0, ...,   1,  10,  14],
        [  1,   2,   1, ...,   2,  23,   9]], dtype=int64)

In [184]:
all_scripts_corpus.shape

(1009, 1313)

In [185]:
cvecscript  = pd.DataFrame(all_scripts_corpus.todense(),
                   columns=cvec.get_feature_names(), index = movies['title'])
cvecscript

10  100  11   12  13  14   15  16  17  \
title                                                                        
10 things i hate about you            1    0   1    1   0   0    0   0   0   
12 and holding                        3    1   3    8   2   2    1   1   1   
12 years a slave                      6    7   7    5   3   3    4   8   3   
127 hours                             7    1   7    4   1   2    8   2   3   
1492: conquest of paradise            0    0   0    0   0   0    0   0   0   
15 minutes                            1    0   0    1   0   0    4   1   0   
17 again                              6    3   2    1   1   1    3   2  17   
2001: a space odyssey                 0    0   0    0   0   0    0   0   0   
2012                                  4    1   1    4   1   2    1   1   2   
25th hour                             1    0   1    2   1   0    3   1   3   
30 minutes or less                    2   14   3    2   4   1   10   1   1   
42                                    6    5   9  154   6  26    6   5   5   
44 inch chest                         4    1   6    6   3   3    5  13   3   
48 hrs.                               1    0   0    0   0   0    0   0   0   
8 mile                                0    0   0    0   0   0    0   0   0   
8mm                                   1    1   0    1   0   0    0   1   1   
9                                     1    0   1    1   1   1    1   1   1   
a few good men                        0    0   0    0   0   3    5   7   1   
a most violent year                   3    1   2    2   1   1    1   2   3   
a scanner darkly                      1    1   7    1   1   4    1   1   1   
a serious man                         1    1   1    2   1   1    1   1   1   
above the law                         3    3   4    2   2   4    6   4  51   
absolute power                        5    3   4    3   4   3    3  54   3   
ace ventura: pet detective            0    0   0    0   0   0    0   0   0   
affliction                            1    1   0    0   2   0    0   0   0   
after school special                  4    4   3    3   3   4    3   4   3   
after.life                            3    1   3    2   1   1    1   1   1   
agnes of god                          0    0   0    0   0   0    1   1   1   
air force one                         0    0   4    0   2   0   28   0   0   
aladdin                               0    0   0    0   0   0    0   0   0   
...                                 ...  ...  ..  ...  ..  ..  ...  ..  ..   
wall street                           6    4   2    6   0   0    6   2   3   
wall street: money never sleeps       0    0   0    0   0   0    0   0   0   
wanted                                2    3   2    4   1   1    1   1   1   
war for the planet of the apes        1    2   1    2   1   1    1   1   1   
war for the planet of the apes        1    2   1    2   1   1    1   1   1   
war for the planet of the apes        1    2   1    2   1   1    1   1   1   
war for the planet of the apes        1    2   1    2   1   1    1   1   1   
war horse                             1    1   1    1   1   2    5   1   1   
war of the worlds                     4    0   0    2   0   0    1   0   0   
warm springs                          4    3   3    4   3   4    4   5   5   
warrior                               7    1   3    5   1   4    3   2   1   
watchmen                              2    3   2    1   8   1    4   1   1   
water for elephants                   1    1   1    1   2   1    1   2   5   
we own the night                      3    1   1    1   3   1    1   1   1   
what lies beneath                     0    0   1    0   0   1    0   0   0   
when a stranger calls                 0    0   0    0   0   0    1   0   1   
while she was out                     3    2   3    3   3   3    3   3   3   
white christmas                       0    0   0    3   0   0    1   0   0   
white squall                          0    0   0    0   1  

In [188]:
for c in cvecscript.columns:
    try:
        float(c)
        cvecscript.drop(c, inplace = True, axis = 1)
    except:
        pass

In [189]:
cvecscript

able  absolutely  act  action  actually  \
title                                                                         
10 things i hate about you             1           1    3       3         7   
12 and holding                         4           0    0       0         3   
12 years a slave                       7           0    6       3         3   
127 hours                              1           2    1       5         3   
1492: conquest of paradise             0           0    0       0         0   
15 minutes                             3           4    1       9         1   
17 again                               2           2    2       0         2   
2001: a space odyssey                  0           0    0       0         0   
2012                                   3           1    3       4         5   
25th hour                              2           1    2       2         2   
30 minutes or less                     1           0    0       2        16   
42                                     5           2    3       1         4   
44 inch chest                          0           1    1       1         0   
48 hrs.                                0           0    0       2         0   
8 mile                                 0           0    0       0         0   
8mm                                    3           2    1       0         1   
9                                      1           0    1       3         1   
a few good men                         4           6    1       1         5   
a most violent year                   12           0    0       2         5   
a scanner darkly                       6           0    3       1         3   
a serious man                          3           6    1       1         3   
above the law                          0           0    1       2         0   
absolute power                         3           0    0       1         1   
ace ventura: pet detective             0           0    0       0         0   
affliction                             2           0    1       1         3   
after school special                   2           2    1      12        11   
after.life                             0           0    0       0         2   
agnes of god                           3           0    1       0         0   
air force one                          2           0    2       5         1   
aladdin                                1           2    0       2         2   
...                                  ...         ...  ...     ...       ...   
wall street                            6           1    2       2         2   
wall street: money never sleeps        0           0    0       0         0   
wanted                                 1           0    1       5         9   
war for the planet of the apes         3           0    1       3         0   
war for the planet of the apes         3           0    1       3         0   
war for the planet of the apes         3           0    1       3         0   
war for the planet of the apes         3           0    1       3         0   
war horse                              3           0    0       4         2   
war of the worlds                      7           2    1       1         0   
warm springs                           8           1    1       0         2   
warrior                                1           3    2       8         4   
watchmen                               4           0    4       5         4   
water for elephants                    2           0   22       0         1   
we own the night                       1           2    1       3         0   
what lies beneath                      1           2    0       0         5   
when a stranger calls                  3           0    1       3         2   
while she was out                      1           0    1       1         0   
white christmas                        4           2    4       3         0   
white s

### Test Train Split CountVectorizer

In [190]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(cvecscript.values, movies['stars_out_of_10']/10)

lr = LinearRegression()




In [191]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((756, 1223), (253, 1223), (756,), (253,))

In [192]:
X_train

array([[ 0,  0,  0, ...,  0,  0,  9],
       [ 1,  1,  1, ...,  0, 22,  7],
       [ 1,  0,  5, ...,  0, 21, 34],
       ...,
       [ 3,  0,  3, ..., 12,  7, 10],
       [ 1,  0,  4, ...,  3,  6,  5],
       [ 2,  1,  1, ...,  1, 18,  5]], dtype=int64)

### Linear Regression CountVectorizer

In [193]:
lr.fit(X_train, y_train)
lr.predict(X_test)

array([ 3.58772430e+10, -1.32903830e+10, -9.41228273e+09,  4.91081836e+09,
       -3.27096615e+10,  2.65803355e+09,  3.24619348e+09, -2.70201683e+10,
       -7.96405673e+09,  1.37615816e+10, -1.14069892e+10, -1.52824714e+10,
        1.20878497e+10, -6.01361806e+09, -7.63314243e+09, -2.17519400e+10,
       -3.12908333e+10,  1.35672244e+10,  9.32611090e+08, -7.74498658e+09,
        6.57485644e-01,  2.92950165e+09, -1.20687681e+10,  6.87671608e+08,
       -9.10435296e+09, -4.87531335e+09, -6.73435401e+09, -2.54528177e+10,
       -9.35779790e+09, -3.37145360e+09,  1.36911200e+10, -8.68991628e+08,
       -1.01369836e+10,  3.51452612e+09,  1.67813859e+10, -5.78667006e+09,
       -7.26631637e+09,  8.19468042e+09, -2.35885301e+10,  1.17880187e+10,
        1.30276738e+10, -5.47553497e+10, -1.16577032e+10, -1.55865021e+10,
        8.99280308e+09,  5.50038744e-01, -4.97236121e+09, -9.58487056e+09,
        4.74063898e+09,  2.39637835e+09,  3.87755505e+09,  3.78995692e+09,
        1.45226347e+09,  

In [194]:
lr.score(X_train, y_train), lr.score(X_test, y_test)

(0.982082569212393, -2.337338162314733e+22)

### Random Forest CountVectorizer

In [195]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()


In [196]:
rf.fit(X_train, y_train)
rf.predict(X_test)

array([0.696     , 0.676     , 0.631     , 0.707     , 0.613     ,
       0.693     , 0.709     , 0.736     , 0.723     , 0.697     ,
       0.683     , 0.681     , 0.698     , 0.753     , 0.689     ,
       0.714     , 0.688     , 0.762     , 0.724     , 0.7       ,
       0.732     , 0.627     , 0.637     , 0.641     , 0.723     ,
       0.739     , 0.636     , 0.636     , 0.723     , 0.622     ,
       0.685     , 0.73      , 0.735     , 0.677     , 0.686     ,
       0.685     , 0.694     , 0.71      , 0.727     , 0.656     ,
       0.666     , 0.683     , 0.713     , 0.647     , 0.773     ,
       0.566     , 0.798     , 0.711     , 0.647     , 0.715     ,
       0.734     , 0.722     , 0.687     , 0.704     , 0.736     ,
       0.67      , 0.692     , 0.672     , 0.686     , 0.689     ,
       0.702     , 0.694     , 0.718     , 0.684     , 0.739     ,
       0.684     , 0.691     , 0.69      , 0.716     , 0.692     ,
       0.678     , 0.712     , 0.751     , 0.646     , 0.715  

In [197]:
rf.score(X_train, y_train), rf.score(X_test, y_test)

(0.8241375671119118, -0.00837103753302948)

In [198]:
#tweak min %, ngrams
#try TFIDF

#word cloud
#graph

#Lasso, Ridge

# TF-IDF the Script Data

In [200]:
from sklearn.feature_extraction.text import TfidfVectorizer
tvec = TfidfVectorizer(stop_words='english', min_df = 0.5, max_df = 0.99)

In [201]:
corpus2 = movies['script']

tvec.fit(corpus2)
all_scripts_corpus2 = tvec.transform(corpus2)
all_scripts_corpus2

<1009x1313 sparse matrix of type '<class 'numpy.float64'>'
	with 943637 stored elements in Compressed Sparse Row format>

In [202]:
all_scripts_corpus2.todense()

matrix([[0.00393999, 0.        , 0.00432249, ..., 0.00481305, 0.02269584,
         0.00337032],
        [0.00906255, 0.00353479, 0.00994236, ..., 0.        , 0.00994356,
         0.00516815],
        [0.0175505 , 0.02395913, 0.02246339, ..., 0.        , 0.04814168,
         0.0225194 ],
        ...,
        [0.00579224, 0.00677768, 0.02541825, ..., 0.25000938, 0.0047665 ,
         0.00165159],
        [0.        , 0.        , 0.        , ..., 0.00182462, 0.01229139,
         0.0178876 ],
        [0.00286289, 0.00669993, 0.00314083, ..., 0.00699456, 0.05418588,
         0.02204063]])

In [203]:
all_scripts_corpus2.shape

(1009, 1313)

In [204]:
tvecscript  = pd.DataFrame(all_scripts_corpus2.todense(),
                   columns=tvec.get_feature_names(), index = movies['title'])
tvecscript

10       100        11        12  \
title                                                                        
10 things i hate about you          0.003940  0.000000  0.004322  0.004166   
12 and holding                      0.009063  0.003535  0.009942  0.025555   
12 years a slave                    0.017550  0.023959  0.022463  0.015466   
127 hours                           0.018506  0.003093  0.020302  0.011182   
1492: conquest of paradise          0.000000  0.000000  0.000000  0.000000   
15 minutes                          0.002850  0.000000  0.000000  0.003014   
17 again                            0.021536  0.012600  0.007876  0.003795   
2001: a space odyssey               0.000000  0.000000  0.000000  0.000000   
2012                                0.010335  0.003023  0.002835  0.010929   
25th hour                           0.002832  0.000000  0.003107  0.005989   
30 minutes or less                  0.005316  0.043540  0.008747  0.005621   
42                                  0.013989  0.013641  0.023021  0.379681   
44 inch chest                       0.013189  0.003858  0.021704  0.020920   
48 hrs.                             0.003095  0.000000  0.000000  0.000000   
8 mile                              0.000000  0.000000  0.000000  0.000000   
8mm                                 0.001735  0.002031  0.000000  0.001835   
9                                   0.004023  0.000000  0.004414  0.004254   
a few good men                      0.000000  0.000000  0.000000  0.000000   
a most violent year                 0.007374  0.002876  0.005393  0.005198   
a scanner darkly                    0.002813  0.003292  0.021604  0.002975   
a serious man                       0.003465  0.004054  0.003801  0.007327   
above the law                       0.007041  0.008239  0.010300  0.004964   
absolute power                      0.011710  0.008221  0.010277  0.007429   
ace ventura: pet detective          0.000000  0.000000  0.000000  0.000000   
affliction                          0.003558  0.004164  0.000000  0.000000   
after school special                0.009455  0.011064  0.007780  0.007499   
after.life                          0.007361  0.002871  0.008076  0.005189   
agnes of god                        0.000000  0.000000  0.000000  0.000000   
air force one                       0.000000  0.000000  0.008788  0.000000   
aladdin                             0.000000  0.000000  0.000000  0.000000   
...                                      ...       ...       ...       ...   
wall street                         0.014297  0.011153  0.005228  0.015118   
wall street: money never sleeps     0.000000  0.000000  0.000000  0.000000   
wanted                              0.005397  0.009473  0.005921  0.011414   
war for the planet of the apes      0.002073  0.004852  0.002275  0.004385   
war for the planet of the apes      0.002073  0.004852  0.002275  0.004385   
war for the planet of the apes      0.002073  0.004852  0.002275  0.004385   
war for the planet of the apes      0.002073  0.004852  0.002275  0.004385   
war horse                           0.002806  0.003284  0.003079  0.002968   
war of the worlds                   0.015958  0.000000  0.000000  0.008437   
warm springs                        0.015321  0.013446  0.012606  0.016201   
warrior                             0.020045  0.003351  0.009425  0.015140   
watchmen                            0.005548  0.009739  0.006087  0.002934   
water for elephants                 0.002530  0.002961  0.002776  0.002675   
we own the night                    0.005196  0.002027  0.001900  0.001831   
what lies beneath                   0.000000  0.000000  0.003720  0.000000   
when a stranger calls               0.000000  0.000000  0.000000  0.000000   
while she was out                   0.007847  0.006121  0.008609  0.008298   
white christmas                     0.000000  0.000000  0.000000  0.012854   
white squall                        0.000000  0.000000  0.000000

In [205]:
for c in tvecscript.columns:
    try:
        float(c)
        tvecscript.drop(c, inplace = True, axis = 1)
    except:
        pass

In [206]:
tvecscript.shape

(1009, 1223)

### Train Test Split TF-IDF

In [207]:
X_train, X_test, y_train, y_test = train_test_split(tvecscript.values, movies['stars_out_of_10']/10)

### Linear Regression on TFIDF

In [208]:
lr.fit(X_train, y_train)
lr.predict(X_test)

array([ 5.06152533e-01, -6.10213688e+10,  1.95283415e+10, -2.38049913e+10,
        6.66382866e-01,  4.65291877e+10, -2.53877503e+09, -7.96375038e+09,
       -6.96291564e+08,  1.76294855e+10, -6.84680967e+09, -2.36478605e+09,
        2.84214483e+10,  5.67049613e+09,  5.29751783e+10, -2.07196907e+10,
       -4.60427596e+10,  1.81425077e+10, -1.47419959e+09,  4.86979995e+10,
       -3.69891577e+10, -1.41226339e+10,  1.42653513e+08,  5.34829832e+09,
       -9.34740200e+09, -2.58373829e+09,  1.44235242e+10, -4.61323692e+10,
       -4.07746509e+10,  2.27497579e+10, -2.43898611e+10, -2.03718682e+10,
       -2.57980739e+10, -2.95780705e+10, -9.84070083e+09, -5.52100148e+10,
        4.33817732e+09, -1.43601171e+10, -4.75537957e+10, -2.52480615e+10,
        6.70957870e+09, -2.10103932e+10, -6.38487540e+10,  2.87806858e+09,
        6.53942116e+10,  6.94318255e+09, -1.25835949e+10,  1.61907536e+10,
        4.21575905e+10,  5.95559888e+10,  1.25296470e+10,  2.15337824e+10,
        2.24005147e+09,  

In [209]:
lr.score(X_train, y_train), lr.score(X_test, y_test)

(0.9950220819292622, -1.1561579668435178e+23)

### Random Forest on TFIDF

In [210]:
rf = RandomForestRegressor()

In [211]:
rf.fit(X_train, y_train)
rf.predict(X_test)

array([0.483     , 0.705     , 0.67      , 0.702     , 0.68925   ,
       0.721     , 0.73      , 0.719     , 0.696     , 0.654     ,
       0.73      , 0.717     , 0.661     , 0.767     , 0.771     ,
       0.631     , 0.716     , 0.728     , 0.686     , 0.697     ,
       0.745     , 0.703     , 0.753     , 0.721     , 0.68      ,
       0.63183333, 0.752     , 0.761     , 0.681     , 0.718     ,
       0.729     , 0.756     , 0.686     , 0.708     , 0.628     ,
       0.653     , 0.666     , 0.616     , 0.757     , 0.717     ,
       0.734     , 0.716     , 0.675     , 0.639     , 0.696     ,
       0.662     , 0.718     , 0.712     , 0.644     , 0.601     ,
       0.642     , 0.671     , 0.651     , 0.619     , 0.751     ,
       0.709     , 0.684     , 0.616     , 0.729     , 0.675     ,
       0.748     , 0.739     , 0.745     , 0.688     , 0.695     ,
       0.666     , 0.73458333, 0.69      , 0.687     , 0.686     ,
       0.713     , 0.639     , 0.622     , 0.668     , 0.662  

In [212]:
rf.score(X_train, y_train), rf.score(X_test, y_test)

(0.8245880232765307, 0.03319593581733438)